
const BEATS = [
  {
    name: "Heaven's Gate Instrumental",
    url: "https://res.cloudinary.com/acushlakoncepts/video/upload/v1646054665/beats/Heaven_s_Gate_Instrumental_oq4kka.wav",
    mood: ["Gentle", "Light", "Sensual", "Relaxation", "Meditation"],
    genre: ["Country", "Jazz", "Blues"],
    collection: "Public Domain",
    trending: true,
    published: '23-02-2022'
  },
   {
    name: "The Evolution of Gayness Instrumental",
    url: "https://res.cloudinary.com/acushlakoncepts/video/upload/v1646054640/beats/The_Evolution_Of_Gayness_Instr_Master_vobplk.wav",
    mood: ["Reggae", "Pop", "Chill Out", "Classical", "Acoustic"],
    genre: ["Sentimental", "Sensual", "Orchestral", "Adventure"],
    collection: "Need for Speed",
    trending: false,
    published: '23-02-2020',
  },
  {
    name: "Ride Electric Instrumental",
    url: "https://res.cloudinary.com/acushlakoncepts/video/upload/v1646054624/beats/Ride_Electric_INST_dfnc74.wav",
    mood: ["Lifestyle", "Nostalgic", "Feel Good"],
    genre: ["Rock", "Electronic", "Electro Pop", "Rock", "Pop"],
    collection: "Need for Speed",
    trending: true,
    published: '21-02-2021',
  },
    {
    name: "Memes Up Instrumental",
    url: "https://res.cloudinary.com/acushlakoncepts/video/upload/v1646054621/beats/Memes_Up_instrumental_cl8veh.wav",
    mood: ["Strange", "Feel Good", "Drama", "Spy"],
    genre: ["Acoustic", "Electro Pop", "Jazz"],
    collection: "Public Domain",
    trending: true,
    published: '23-04-2021',
  },

  {
    name: "Freedom Remix Instrumental",
    url: "https://res.cloudinary.com/acushlakoncepts/video/upload/v1646054602/beats/Freedom_Remix_INST_iyj9ct.wav",
    mood: ["Lifestyle", "Magical", "Mistical", "Sci-Fi", "Future", "Aggressive"],
    genre: ["Production", "Jazz", "Trailer", "Techno"],
    collection: "Need for Speed",
    trending: false,
    published: '10-02-2021',
  },

  {
    name: "Freedom Remix Instrumental",
    url: "https://res.cloudinary.com/acushlakoncepts/video/upload/v1646054602/beats/Freedom_Remix_INST_iyj9ct.wav",
    mood: ["Lifestyle", "Magical", "Mistical", "Sci-Fi", "Future", "Aggressive"],
    genre: ["Production", "Jazz", "Trailer", "Techno"],
    collection: "Need for Speed",
    trending: true,
    published: '02-02-2022',
  }
]

const GENRES = [
  "Acoustic",
  "Ambient",
  "Audio Logos",
  "Blues",
  "Chill Out",
  "Christmas",
  "Classical",
  "Corporate",
  "Country",
  "Dance / Techno",
  "Dubstep",
  "Easy Listening",
  "Electro Pop",
  "Electronic",
  "Folk",
  "Games",
  "Hip Hop",
  "Holiday",
  "Independent",
  "Indie Pop",
  "Jazz",
  "Kids / Children",
  "Latin",
  "Masterworks",
  "Motown",
  "New Age",
  "News",
  "Piano / Solo Instrumental",
  "Pop",
  "Production / Film Scores",
  "R&B",
  "Reggae",
  "Rock",
  "Trailer",
  "Vocals",
  "World",
]


const MOODS = [
  "Action / Sports",
  "Adventure / Discovery",
  "Aerobics / Workout",
  "Aggressive",
  "Comedy / Funny",
  "Crime / Thriller / Spy",
  "Dark / Somber",
  "Epic / Orchestral",
  "Fashion / Lifestyle",
  "Feel Good",
  "Gentle / Light",
  "Happy / Cheerful",
  "Horror / Scary",
  "Magical / Mystical",
  "Military / Patriotic",
  "Relaxation / Meditation",
  "Religious / Christian",
  "Romantic / Sentimental",
  "Sad / Nostalgic",
  "Sci-Fi / Future",
  "Sexy / Sensual",
  "Strange / Bizarre",
  "Suspense / Drama",
  "Underscores",
  "Uplifting",
  "Wedding"
]

export { MOODS, GENRES, BEATS }